# render.yaml
services:
  - type: web
    name: infohub
    runtime: python
    repo: https://github.com/infohub007/infohub
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false